name: Build Trainer and Client APKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-trainer-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Build Trainer APK
        run: |
          cd mobile_apps/dog_trainer_app
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload Trainer APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trainer-app-release
          path: mobile_apps/dog_trainer_app/build/app/outputs/flutter-apk/app-release.apk

  build-client-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Build Client APK
        run: |
          cd mobile_apps/dog_client_app
          flutter pub get
          flutter build apk --release --no-tree-shake-icons

      - name: Upload Client APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-app-release
          path: mobile_apps/dog_client_app/build/app/outputs/flutter-apk/app-release.apk
